apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../openshift/application/cert-manager
images:
- name: quay.io/jetstack/cert-manager-controller
  newName: quay.io/ibm/cert-manager-controller-ppc64le
  newTag: v0.11.0
- name: quay.io/jetstack/cert-manager-webhook
  newName: quay.io/ibm/cert-manager-webhook-ppc64le
  newTag: v0.11.0
- name: quay.io/jetstack/cert-manager-cainjector
  newName: quay.io/ibm/cert-manager-cainjector-ppc64le
  newTag: v0.11.0
