apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../openshift/application/tensorboard
images:
- name: public.ecr.aws/j1r0q0g6/notebooks/tensorboards-web-app
  newName: quay.io/ibm/kubeflow-tensorboards-web-app-ppc64le
  newTag: v1.3.0-rc.1
- name: public.ecr.aws/j1r0q0g6/notebooks/tensorboard-controller
  newName: quay.io/ibm/kubeflow-tensorboard-controller-ppc64le
  newTag: v1.3.0-rc.1
- name: gcr.io/kubebuilder/kube-rbac-proxy
  newName: quay.io/ibm/kubeflow-kube-rbac-proxy-ppc64le
  newTag: v0.4.0
