apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../openshift
images:
- name: public.ecr.aws/j1r0q0g6/notebooks/access-management
  newName: quay.io/ibm/kubeflow-access-management-ppc64le
  newTag: v1.3.0-rc.1
- name: quay.io/kubeflow/profile-controller
  newName: quay.io/ibm/kubeflow-profile-controller-ppc64le
  newTag: v0.8.0
- name: public.ecr.aws/j1r0q0g6/notebooks/central-dashboard
  newName: quay.io/ibm/kubeflow-central-dashboard-ppc64le
  newTag: v1.3.0-rc.1
- name: public.ecr.aws/j1r0q0g6/notebooks/admission-webhook
  newName: quay.io/ibm/kubeflow-admission-webhook-ppc64le
  newTag: v1.3.0-rc.1

