apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app.kubernetes.io/component: cert-manager
  app.kubernetes.io/name: cert-manager
  kustomize.component: cert-manager
kind: Kustomization
namespace: cert-manager
resources:
- ../../../../cert-manager/cert-manager/base
- ../../../../cert-manager/cert-manager/overlays/application/application.yaml
- ../../../../cert-manager/cert-manager/overlays/self-signed/cluster-issuer.yaml
configurations:
- ../../../../cert-manager/cert-manager/overlays/application/params.yaml
images:
- name: quay.io/jetstack/cert-manager-controller
  newName: docker.io/lehrig/cert-manager-controller
  newTag: v0.11.0.ppc64le
- name: quay.io/jetstack/cert-manager-webhook
  newName: docker.io/lehrig/cert-manager-webhook
  newTag: v0.11.0.ppc64le
- name: quay.io/jetstack/cert-manager-cainjector
  newName: docker.io/lehrig/cert-manager-cainjector
  newTag: v0.11.0.ppc64le
