apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- ../../../../pipeline/minio/installs/generic
- ../../../../pipeline/mysql/installs/generic
# For now we dont have authentication and istio injection disabled
# TODO tie into OCP oauth
#- ../../../../pipeline/installs/multi-user
- ../../../../pipeline/installs/generic
# Disabling tls traffic in Destination Rule because of issue: https://github.com/kubeflow/kubeflow/issues/5271
patches:
- target:
    kind: DestinationRule
    version: v1alpha3
    group: networking.istio.io
    name: ml-pipeline-ui
  path: patchuirule.yaml

#Only for multi-user
configMapGenerator:
#- name: kubeflow-pipelines-profile-controller-code
#  behavior: replace
#  files:
#  - sync.py
#commenting these out for now since pipelines has to be installed in main kustomize because of
# the dependency on profiles
- name: kubeflow-config
  envs:
  - ../../config/params.env
vars:
- fieldref:
    fieldPath: data.clusterDomain
  name: clusterDomain
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kubeflow-config
- fieldref:
    fieldPath: metadata.namespace
  name: namespace
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kubeflow-config
images:
- name: gcr.io/ml-pipeline/minio
  newTag: RELEASE.2019-04-09T01-22-30Z.1
  newName: image-registry.openshift-image-registry.svc:5000/openshift/minio
- name: gcr.io/ml-pipeline/mysql
  newTag: 10.2.19
  newName: image-registry.openshift-image-registry.svc:5000/openshift/mariadb
- name: gcr.io/ml-pipeline/api-server
  newTag: v1.0.4.ppc64le
  newName: image-registry.openshift-image-registry.svc:5000/openshift/api-server
- name: gcr.io/ml-pipeline/persistenceagent
  newTag: v1.0.4.ppc64le
  newName: image-registry.openshift-image-registry.svc:5000/openshift/persistent-agent
- name: gcr.io/ml-pipeline/scheduledworkflow
  newTag: v1.0.4.ppc64le
  newName: image-registry.openshift-image-registry.svc:5000/openshift/scheduledworkflow
- name: gcr.io/ml-pipeline/frontend
  newTag: v1.0.4.ppc64le
  newName: image-registry.openshift-image-registry.svc:5000/openshift/pipelines-ui
- name: gcr.io/ml-pipeline/viewer-crd-controller
  newTag: v1.0.4.ppc64le
  newName: image-registry.openshift-image-registry.svc:5000/openshift/pipelines-viewer
- name: gcr.io/ml-pipeline/visualization-server
  newTag: v1.0.4.ppc64le
  newName: image-registry.openshift-image-registry.svc:5000/openshift/visualization-server 
