apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-sidecar-injector
  labels:
    app: istio
    istio: sidecar-injector
data:
  config: |-
    template: |-
      initContainers:
        securityContext:
          privileged: true
