apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- crds.yaml
- ../../../../argo/base_v3
patchesStrategicMerge:
- crds_patch.yaml
configMapGenerator:
- name: workflow-controller-parameters
  behavior: merge
  literals:
  - containerRuntimeExecutor=pns  #old value: k8sapi
  - executorImage=image-registry.openshift-image-registry.svc:5000/openshift/argoexec:v2.8.2.ppc64le
- name: kubeflow-config
  envs:
  - ../../config/params.env
# We need to define vars at the top level otherwise we will get
# conflicts.
vars:
- fieldref:
    fieldPath: data.clusterDomain
  name: clusterDomain
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kubeflow-config
- fieldref:
    fieldPath: metadata.namespace
  name: namespace
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kubeflow-config
images:
- name: argoproj/argoui
  newTag: 2.3.0-ppc64le
  newName: image-registry.openshift-image-registry.svc:5000/openshift/argoui
- name: argoproj/workflow-controller
  newTag: v2.8.2.ppc64le
  newName: image-registry.openshift-image-registry.svc:5000/openshift/workflow-controller
- name: argoproj/argoexec
  newTag: v2.8.2.ppc64le
  newName: image-registry.openshift-image-registry.svc:5000/openshift/argoexec

