apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
- ../../../../metacontroller/base
images:
- name: metacontroller/metacontroller
  newName: docker.io/lehrig/metacontroller
  newTag: v0.3.0.ppc64le
